### ISSUE TITLE
5_0 content <style> issue 

### ISSUE THREAD

**Issue by RNCST** [RNCST/K80_FRONT_PRAC#21]
#19 @kappleword 

5_0 content <style> issue 

```
  <style>
    body {
      background-color: #fafafa;
    }

    .container {
      margin: 150px auto;
      max-width: 960px;
    }
  </style>
```

이와 같이 body같은 전역 태그속에 이 html에서만 쓰는 스타일을 접목하면 다 같이 합쳣을때 스타일 적용도 힘들뿐더러
관리가 힘드니까 따로 id를 부여해서 스탕리 부여를 해주세요

**Comment by kappleword** [comment]
문제부분 안쓰이는 기능같아서 삭제했습니다.
